# Generated by Django 6.0.6 on 2026-09-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_jewelryproduct_gift_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelryproduct',
            name='age_group',
            field=models.CharField(blank=True, choices=[('', 'All'), ('newborn', 'Newborn (0-1 month)'), ('infant', 'Infant (1 month-1 year)'), ('toddler', 'Toddler (1-3 years)'), ('child', 'Child (3-9 years)'), ('preteen', 'Preteen (9-12 years)'), ('teenager', 'Teenager (13-19 years)'), ('young_adult', 'Young Adult (20-29 years)'), ('adult', 'Adult (30-44 years)'), ('middle_aged', 'Middle-aged (45-64 years)'), ('senior', 'Senior (65-79 years)'), ('elderly', 'Elderly (80-99 years)'), ('centenarian', 'Centenarian (100+ years)')], max_length=20),
        ),
    ]
