# Generated by Django 6.0.6 on 2026-09-10 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_jewelryproduct_age_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelryproduct',
            name='is_internal_asset',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='JewelryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reject_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jewelry_requests_made', to=settings.AUTH_USER_MODEL)),
                ('requested_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jewelry_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JewelryRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_items', to='accounts.jewelryproduct')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.jewelryrequest')),
            ],
        ),
        migrations.CreateModel(
            name='JewelryStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_holdings', to='accounts.jewelryproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jewelry_stock', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='jewelryrequest',
            index=models.Index(fields=['requested_to', 'status', 'created_at'], name='accounts_je_request_ce26f9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jewelrystock',
            unique_together={('user', 'product')},
        ),
    ]
