# Generated by Django 6.0.6 on 2026-09-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_jewelryproduct_is_internal_asset_jewelryrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelryproduct',
            name='category',
            field=models.CharField(choices=[('goldcoin', 'Gold Coin'), ('rings', 'Rings'), ('necklaces', 'Necklaces'), ('bangles', 'Bangles'), ('bracelets', 'Bracelets'), ('earrings', 'Earrings'), ('chains', 'Chains'), ('pendants', 'Pendants'), ('mangalsutra', 'Mangalsutra'), ('maangtikka', 'Maang Tikka'), ('anklets', 'Anklets'), ('nosepin', 'Nose Pin'), ('toerings', 'Toe Rings'), ('cufflinks', 'Cufflinks'), ('brooches', 'Brooches'), ('tiepins', 'Tie Pins'), ('coins', 'Coins'), ('kada', 'Kada'), ('earchains', 'Ear Chains'), ('armlets', 'Armlets'), ('goldbars', 'Gold Bars'), ('silvercoins', 'Silver Coins'), ('silverbars', 'Silver Bars'), ('articles', 'Articles')], max_length=20),
        ),
    ]
