# Generated by Django 6.0.6 on 2026-09-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_ordertrackingevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinrecharge',
            name='commission_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
