# Generated by Django 6.0.6 on 2026-09-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_alter_coinrecharge_commission_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinrecharge',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('upi', 'UPI'), ('netbanking', 'Netbanking'), ('wallet', 'Wallet'), ('commission', 'Commission'), ('purchase', 'Purchase'), ('admin', 'BBTEAM'), ('reward', 'Login Reward'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='coinrecharge',
            name='source',
            field=models.CharField(choices=[('recharge', 'Recharge'), ('commission', 'Commission'), ('purchase', 'Purchase'), ('admin_credit', 'BBTEAM Credit'), ('reward', 'Login Reward')], default='recharge', max_length=20),
        ),
    ]
