# Generated by Django 6.0.6 on 2026-09-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_coinrequest_approved_by_jewelryrequest_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelryproduct',
            name='occasion',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
