# Generated by Django 6.0.6 on 2026-09-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0062_alter_jewelryproduct_occasion'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelryproduct',
            name='die_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
