# Generated by Django 4.2.11 on 2026-09-29 05:11

from django.db import migrations, models
from django.db.models import OuterRef, Subquery


def backfill_order_weight(apps, schema_editor):
    # Pazhaya orders-ku ippo irukura product weight-a oru dhadava copy panni freeze pannurom —
    # idhukku appuram product weight maathinaalum order-la maaraadhu
    JewelryOrder = apps.get_model('accounts', 'JewelryOrder')
    JewelryProduct = apps.get_model('accounts', 'JewelryProduct')
    JewelryOrder.objects.filter(product_net_weight__isnull=True, product__isnull=False).update(
        product_net_weight=Subquery(
            JewelryProduct.objects.filter(id=OuterRef('product_id')).values('net_weight')[:1]
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_jewelryproduct_die_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelryorder',
            name='product_net_weight',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.RunPython(backfill_order_weight, migrations.RunPython.noop),
    ]
