# Generated by Django 4.2.11 on 2026-09-29 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_jewelryrequest_forwarded_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('jewellery', 'Jewellery'), ('coin', 'Coin')], db_index=True, max_length=10)),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_phone', models.CharField(max_length=15)),
                ('product_name', models.CharField(blank=True, max_length=200)),
                ('product_code', models.CharField(blank=True, max_length=50)),
                ('product_image_url', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=30)),
                ('coin_metal_type', models.CharField(blank=True, max_length=20)),
                ('coin_weight_label', models.CharField(blank=True, max_length=20)),
                ('metal', models.CharField(blank=True, max_length=20)),
                ('grade', models.CharField(blank=True, max_length=10)),
                ('gross_weight', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('net_weight', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('rate_per_gram', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('making_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('stone_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('die_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=3, max_digits=5)),
                ('mrp_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='completed', max_length=10)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_sales', to='accounts.jewelryproduct')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['seller', 'kind', 'created_at'], name='accounts_st_seller__fcff4e_idx'), models.Index(fields=['kind', 'status', 'created_at'], name='accounts_st_kind_5d0596_idx')],
            },
        ),
    ]
