# Generated by Django 4.2.11 on 2026-09-30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0066_stocksale'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinrequest',
            name='forwarded_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upstream_requests', to='accounts.coinrequest'),
        ),
    ]
