# Generated by Django 6.0.6 on 2026-10-07 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0067_coinrequest_forwarded_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigiGoldInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('buy', 'Buy Gold'), ('sell', 'Sell Gold'), ('convert', 'Convert from Recharge / Wallet')], default='buy', max_length=20)),
                ('recharge_amount', models.DecimalField(decimal_places=2, help_text='INR invested or recharged', max_digits=12)),
                ('gold_price_per_gram', models.DecimalField(decimal_places=2, help_text='Gold rate per gram at transaction time', max_digits=12)),
                ('mg_price', models.DecimalField(decimal_places=4, help_text='Rate per mg = gold_price_per_gram / 1000', max_digits=12)),
                ('hold_gold_mg', models.DecimalField(decimal_places=4, help_text='Milligrams of gold (recharge_amount / mg_price)', max_digits=14)),
                ('hold_gold_gm', models.DecimalField(decimal_places=6, help_text='Grams of gold (hold_gold_mg / 1000)', max_digits=14)),
                ('payment_method', models.CharField(default='recharge_conversion', max_length=40)),
                ('transaction_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], db_index=True, default='completed', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digi_gold_investments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DigiGoldWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_gold_mg', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('total_gold_gm', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('total_invested_inr', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digi_gold_wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
