// categoryConfig.js
// Shared subcategory list — Navbar, Super Admin product form, AllCollection.jsx
// moonu file-um idha irundhu than data edukkum. Puthu subcategory add pannanumna
// idhula oru line add pannina podhum — moonu place-layum automatic-a varum.

export const CATEGORY_SUBCATEGORIES = {
  goldcoin: {
    gold: ["50 mg Gold Coin", "100 mg Gold Coin", "200 mg Gold Coin", "250 mg Gold Coin", "500 mg Gold Coin", "1 gm Gold Coin", "2 gm Gold Coin", "4 gm Gold Coin", "8 gm Gold Coin", "16 gm Gold Coin", "40 gm Gold Coin", "Gold Lakshmi Coin", "Gold Ganesha Coin", "Gold Gift Coin"],
    silver: ["250 mg Silver Coin", "500 mg Silver Coin", "1 gm Silver Coin", "2 gm Silver Coin", "5 gm Silver Coin", "10 gm Silver Coin", "20 gm Silver Coin", "50 gm Silver Coin", "100 gm Silver Coin", "Silver Lakshmi Coin", "Silver Ganesha Coin", "Silver Gift Coin"],
  },
  rings: {
    gold: [
      "Daily Wear Gold Rings",
      "Lightweight Gold Rings",
      "Women's Gold Rings",
      "Men's Gold Rings",
      "Couple Gold Rings",
      "Engagement Gold Rings",
      "Diamond Gold Rings",
      "Designer Gold Rings",
      "Personalized Gold Rings",
      "Traditional Gold Rings",
      "Kids Gold Rings",
      "Plain Gold Rings",
      "Gemstone Gold Rings",
    ],
    silver: [
      "Daily Wear Silver Rings",
      "Women's Silver Rings",
      "Men's Silver Rings",
      "Kids Silver Rings",
      "Couple Silver Rings",
      "Adjustable Silver Rings",
      "Designer Silver Rings",
      "Stone Silver Rings",
      "Personalized Silver Rings",
      "Plain Silver Rings",
      "Oxidised Silver Rings",
    ],
    wedding: ["Engagement Rings", "Wedding Rings", "Kundan Rings", "Temple Rings", "Couple Rings", "Antique Rings", "Polki Rings"],
  },
  earrings: {
    gold: [
      "Daily Wear Gold Earrings",
      "Lightweight Gold Earrings",
      "Stud Earrings",
      "Women's Gold Earrings",
      "Traditional Gold Earrings",
      "Designer Gold Earrings",
      "Jhumka Earrings",
      "Hoop Earrings",
      "Diamond Gold Earrings",
      "Kids Earrings",
      "Drop Earrings",
      "Sui Dhaga Earrings",
    ],
    silver: [
      "Daily Wear Silver Earrings",
      "Silver Stud Earrings",
      "Silver Jhumka Earrings",
      "Silver Hoop Earrings",
      "Women's Silver Earrings",
      "Kids Silver Earrings",
      "Designer Silver Earrings",
      "Traditional Silver Earrings",
      "Stone Silver Earrings",
      "Drop Silver Earrings",
      "Oxidised Earrings",
      "Chandbali Earrings",
      "Ear Cuffs",
    ],
    wedding: ["Jhumka Earrings", "Kundan Earrings", "Temple Earrings", "Chandbali Earrings", "Polki Earrings", "Long Earrings", "Stud Earrings", "Drop Earrings"],
  },
  bangles: {
    gold: [
      "Daily Wear Gold Bangles",
      "Lightweight Gold Bangles",
      "Women's Gold Bangles",
      "Traditional Gold Bangles",
      "Designer Gold Bangles",
      "Bridal Gold Bangles",
      "Diamond Gold Bangles",
      "Personalized Gold Bangles",
      "Kids Gold Bangles",
      "Plain Gold Bangles",
    ],
    silver: [
      "Daily Wear Silver Bangles",
      "Lightweight Silver Bangles",
      "Women's Silver Bangles",
      "Traditional Silver Bangles",
      "Designer Silver Bangles",
      "Kids Silver Bangles",
      "Plain Silver Bangles",
      "Oxidised Bangles",
      "Kada Bangles",
      "Stone Bangles",
      "Beaded Bangles",
      "Adjustable Bangles",
    ],
    wedding: ["Gold Bangles", "Kundan Bangles", "Antique Bangles", "Polki Bangles", "Kada Bangles", "Temple Bangles", "Designer Bangles", "Bangle Sets"],
  },
  bracelets: {
    gold: [
      "Daily Wear Gold Bracelets",
      "Lightweight Gold Bracelets",
      "Women's Gold Bracelets",
      "Men's Gold Bracelets",
      "Couple Gold Bracelets",
      "Designer Gold Bracelets",
      "Diamond Gold Bracelets",
      "Chain Gold Bracelets",
      "Personalized Gold Bracelets",
      "Kids Gold Bracelets",
      "Gold Plain Bracelet",
      "Gold Bridal Bracelet",
      "Gold Stone Bracelet",
      "Gold Charm Bracelet",
    ],
    silver: [
      "Daily Wear Silver Bracelets",
      "Lightweight Silver Bracelets",
      "Women's Silver Bracelets",
      "Men's Silver Bracelets",
      "Kids Silver Bracelets",
      "Couple Silver Bracelets",
      "Chain Silver Bracelets",
      "Designer Silver Bracelets",
      "Personalized Silver Bracelets",
      "Charms Bracelets",
      "Cuff Bracelets",
      "ID Bracelets",
      "Beaded Bracelets",
      "Mangalsutra Bracelets",
    ],
  },
  pendants: {
    gold: [
      "Daily Wear Gold Pendants",
      "Lightweight Gold Pendants",
      "Women's Gold Pendants",
      "Men's Gold Pendants",
      "Traditional Gold Pendants",
      "Designer Gold Pendants",
      "Diamond Gold Pendants",
      "Personalized Gold Pendants",
      "Religious Gold Pendants",
      "Kids Gold Pendants",
      "Initial Pendants",
      "Gemstone Pendants",
    ],
    silver: [
      "Daily Wear Silver Pendants",
      "Lightweight Silver Pendants",
      "Women's Silver Pendants",
      "Men's Silver Pendants",
      "Religious Silver Pendants",
      "Personalized Silver Pendants",
      "Stone Silver Pendants",
      "Initial Pendants",
      "Heart Pendants",
      "Kids Pendants",
      "Motif Pendants",
      "Oxidised Pendants",
    ],
  },
  chains: {
    gold: [
      "Daily Wear Gold Chains",
      "Lightweight Gold Chains",
      "Men's Gold Chains",
      "Women's Gold Chains",
      "Traditional Gold Chains",
      "Designer Gold Chains",
      "Rope Gold Chains",
      "Fancy Gold Chains",
      "Diamond Gold Chains",
      "Kids Gold Chains",
      "Plain Gold Chains",
      "Box Chains",
      "Figaro Chains",
      "Beaded Chains",
    ],
    silver: [
      "Daily Wear Silver Chains",
      "Lightweight Silver Chains",
      "Men's Silver Chains",
      "Women's Silver Chains",
      "Kids Silver Chains",
      "Traditional Silver Chains",
      "Designer Silver Chains",
      "Fancy Silver Chains",
      "Plain Silver Chains",
      "Rope Chains",
      "Box Chains",
      "Figaro Chains",
      "Beaded Chains",
    ],
  },
  necklaces: {
    gold: [
      "Daily Wear Gold Necklaces",
      "Lightweight Gold Necklaces",
      "Women's Gold Necklaces",
      "Traditional Gold Necklaces",
      "Designer Gold Necklaces",
      "Bridal Gold Necklaces",
      "Diamond Gold Necklaces",
      "Layered Gold Necklaces",
      "Personalized Gold Necklaces",
      "Kids Gold Necklaces",
      "Plain Gold Necklaces",
      "Temple Necklaces",
      "Chain Necklaces",
      "Mangalsutra Necklaces",
    ],
    silver: [
      "Daily Wear Silver Necklaces",
      "Lightweight Silver Necklaces",
      "Women's Silver Necklaces",
      "Traditional Silver Necklaces",
      "Designer Silver Necklaces",
      "Layered Silver Necklaces",
      "Statement Silver Necklaces",
      "Chains",
      "Pendant Necklaces",
      "Choker Necklaces",
      "Oxidised Necklaces",
      "Beaded Necklaces",
      "Mangalsutra Necklaces",
    ],
    wedding: ["Temple Necklaces", "Kundan Necklaces", "Antique Necklaces", "Polki Necklaces", "Traditional Necklaces", "Long Haaram", "Choker Necklaces", "Rani Haar"],
  },
  mangalsutra: {
    gold: [
      "Daily Wear Gold Mangalsutras",
      "Lightweight Gold Mangalsutras",
      "Traditional Gold Mangalsutras",
      "Designer Gold Mangalsutras",
      "Bridal Gold Mangalsutras",
      "Short Gold Mangalsutras",
      "Long Gold Mangalsutras",
      "Black Bead Gold Mangalsutras",
      "Diamond Gold Mangalsutras",
      "Personalized Gold Mangalsutras",
      "Beaded Mangalsutra",
      "Gold Mangalsutra Set",
    ],
    silver: ["Silver Mangalsutra", "Silver Black Bead Mangalsutra", "Silver Short Mangalsutra"],
    wedding: ["Traditional Mangalsutra", "Beaded Mangalsutra", "Pendant Mangalsutra", "Short Mangalsutra", "Gold Mangalsutra", "Black Bead Mangalsutra", "Mangalsutra Sets"],
  },
  anklets: {
    gold: [
      "Daily Wear Gold Anklets",
      "Lightweight Gold Anklets",
      "Women's Gold Anklets",
      "Traditional Gold Anklets",
      "Designer Gold Anklets",
      "Bridal Gold Anklets",
      "Fancy Gold Anklets",
      "Chain Gold Anklets",
      "Diamond Gold Anklets",
      "Kids Gold Anklets",
      "Gold Anklets",
      "Beaded Gold Anklets",
    ],
    silver: [
      "Daily Wear Silver Anklets",
      "Lightweight Silver Anklets",
      "Traditional Silver Anklets",
      "Designer Silver Anklets",
      "Kids Silver Anklets",
      "Plain Silver Anklets",
      "Oxidised Anklets",
      "Beaded Anklets",
      "Charm Anklets",
      "Pair Anklets",
      "Temple Anklets",
    ],
  },
  coins: {
    gold: [
      "50 mg Gold Coin",
      "100 mg Gold Coin",
      "200 mg Gold Coin",
      "250 mg Gold Coin",
      "500 mg Gold Coin",
      "1 gm Gold Coin",
      "2 gm Gold Coin",
      "4 gm Gold Coin",
      "8 gm Gold Coin",
      "16 gm Gold Coin",
      "40 gm Gold Coin",
      "Gold Lakshmi Coin",
      "Gold Ganesha Coin",
      "Gold Gift Coin",
      "Gold Coins",
      "Gold Bars",
    ],
    silver: [
      "250 mg Silver Coin",
      "500 mg Silver Coin",
      "1 gm Silver Coin",
      "2 gm Silver Coin",
      "5 gm Silver Coin",
      "10 gm Silver Coin",
      "20 gm Silver Coin",
      "50 gm Silver Coin",
      "100 gm Silver Coin",
      "Silver Lakshmi Coin",
      "Silver Ganesha Coin",
      "Silver Gift Coin",
    ],
  },
  nosepin: {
    gold: [
      "Daily Wear Gold Nose Pins",
      "Lightweight Gold Nose Pins",
      "Women's Gold Nose Pins",
      "Diamond Gold Nose Pins",
      "Traditional Gold Nose Pins",
      "Designer Gold Nose Pins",
      "Floral Gold Nose Pins",
      "Stud Gold Nose Pins",
      "Stone Gold Nose Pins",
      "Kids Gold Nose Pins",
      "Gold Nose Pin",
      "Gold Hoop Nose Pin",
      "Bridal Gold Nose Pin",
    ],
    silver: [
      "Daily Wear Silver Nose Pins",
      "Lightweight Silver Nose Pins",
      "Women's Silver Nose Pins",
      "Traditional Silver Nose Pins",
      "Stone Silver Nose Pins",
      "Designer Silver Nose Pins",
      "Silver Nose Pin",
      "Oxidised Silver Nose Pin",
      "Silver Stud Nose Pin",
    ],
  },
  // toerings, cufflinks, brooches, tiepins, kada, earchains, armlets, bars, articles
  toerings: {
    gold: [
      "Daily Wear Gold Toe Rings",
      "Lightweight Gold Toe Rings",
      "Traditional Gold Toe Rings",
      "Women's Gold Toe Rings",
      "Designer Gold Toe Rings",
      "Gold Toe Rings",
      "Bridal Gold Toe Rings",
    ],
    silver: [
      "Daily Wear Silver Toe Rings",
      "Lightweight Silver Toe Rings",
      "Traditional Silver Toe Rings",
      "Designer Silver Toe Rings",
      "Adjustable Silver Toe Rings",
      "Plain Silver Toe Rings",
      "Oxidised Silver Toe Rings",
    ],
  },
  cufflinks: { gold: ["Gold Cufflinks", "Wedding Cufflinks"], silver: ["Silver Cufflinks"] },
  brooches: { gold: ["Gold Brooch"], silver: ["Silver Brooch"] },
  tiepins: {
    gold: [
      "Daily Wear Gold Tie Pins",
      "Lightweight Gold Tie Pins",
      "Men's Gold Tie Pins",
      "Designer Gold Tie Pins",
      "Diamond Gold Tie Pins",
      "Traditional Gold Tie Pins",
      "Personalized Gold Tie Pins",
      "Simple Gold Tie Pins",
      "Fancy Gold Tie Pins",
      "Luxury Gold Tie Pins",
      "Gold Tie Pin",
    ],
    silver: ["Silver Tie Pin"],
  },
  maangtikka: {
    gold: [
      "Traditional Gold Maang Tikka",
      "Bridal Gold Maang Tikka",
      "Lightweight Gold Maang Tikka",
      "Designer Gold Maang Tikka",
      "Diamond Gold Maang Tikka",
      "Gold Maang Tikka",
    ],
    silver: ["Silver Maang Tikka"],
  },
  kada: {
    gold: [
      "Daily Wear Gold Kada",
      "Lightweight Gold Kada",
      "Men's Gold Kada",
      "Women's Gold Kada",
      "Traditional Gold Kada",
      "Designer Gold Kada",
      "Diamond Gold Kada",
      "Plain Gold Kada",
      "Gents Kada",
    ],
    silver: ["Plain Silver Kada", "Designer Silver Kada"],
  },
  earchains: {
    gold: [
      "Traditional Gold Ear Chains",
      "Bridal Gold Ear Chains",
      "Lightweight Gold Ear Chains",
      "Designer Gold Ear Chains",
      "Diamond Gold Ear Chains",
      "Gold Ear Chain",
    ],
    silver: ["Silver Ear Chain"],
  },
  armlets: {
    gold: [
      "Traditional Gold Armlets",
      "Bridal Gold Armlets",
      "Lightweight Gold Armlets",
      "Designer Gold Armlets",
      "Diamond Gold Armlets",
      "Bridal Vanki Armlet",
    ],
    silver: ["Silver Armlet"],
  },
  goldbars: { gold: ["1g Gold Bar", "2g Gold Bar", "5g Gold Bar", "10g Gold Bar", "20g Gold Bar", "50g Gold Bar", "100g Gold Bar"], silver: [] },
  silvercoins: {
    gold: [],
    silver: [
      "250 mg Silver Coin",
      "500 mg Silver Coin",
      "1 gm Silver Coin",
      "2 gm Silver Coin",
      "5 gm Silver Coin",
      "10 gm Silver Coin",
      "20 gm Silver Coin",
      "50 gm Silver Coin",
      "100 gm Silver Coin",
      "Silver Lakshmi Coin",
      "Silver Ganesha Coin",
      "Silver Gift Coin",
    ],
  },
  silverbars: { gold: [], silver: ["10g Silver Bar", "20g Silver Bar", "50g Silver Bar", "100g Silver Bar", "250g Silver Bar", "500g Silver Bar", "1kg Silver Bar"] },
  articles: {
    gold: [],
    silver: [
      "Silver Pooja Articles",
      "Silver God Idols",
      "Silver Coins",
      "Silver Gift Articles",
      "Silver Baby Gift Articles",
      "Silver Dining Articles",
      "Silver Utility Articles",
      "Silver Pooja Thali",
      "Silver Diya",
      "Silver Glass",
      "Silver Bowl",
    ],
  },
};

// Category-level metadata — Navbar mega menu title/icon/route ku
export const CATEGORY_META = {
  rings:      { title: "Rings",      icon: "◌" },
  earrings:   { title: "Earrings",   icon: "♢" },
  bangles:    { title: "Bangles",    icon: "◯" },
  bracelets:  { title: "Bracelets",  icon: "◌" },
  pendants:   { title: "Pendants",   icon: "♤" },
  chains:     { title: "Chains",     icon: "⌁" },
  necklaces:  { title: "Necklaces",  icon: "♧" },
  mangalsutra:{ title: "Mangalsutra",icon: "♧" },
  anklets:    { title: "Anklets",    icon: "⌁" },
  coins:      { title: "Coins",      icon: "◎" },
};

export function getSubcategories(category, metal) {
  if (category === 'coins') {
    return CATEGORY_SUBCATEGORIES.coins?.[metal] || CATEGORY_SUBCATEGORIES.goldcoin?.[metal] || [];
  }
  if (category === 'silvercoins') {
    return CATEGORY_SUBCATEGORIES.silvercoins?.[metal] || CATEGORY_SUBCATEGORIES.coins?.[metal] || [];
  }
  return CATEGORY_SUBCATEGORIES[category]?.[metal] || [];
}

// ── Gifting — thani structure, metal/category illama gift_tag vachi
// group aaguthu. Ovvoru tag-kkum keezhe gift_type options iruku ──
export const GIFTING_SUBCATEGORIES = {
  Her: ["Necklaces", "Earrings", "Rings", "Bracelets", "Pendants", "Bangles", "Mangalsutra", "Nose Pins"],
  Him: ["Chains", "Bracelets", "Rings", "Pendants", "Cufflinks", "Tie Pins", "Men's Kada", "Coins & Bars"],
  Kids: ["Baby Jewellery", "Chains", "Earrings", "Bracelets", "Nazariya", "Anklets", "Pendants", "ID Bracelets"],
  Couple: ["Couple Rings", "Couple Pendants", "Matching Bracelets", "His & Her Sets", "Engagement Gifts", "Anniversary Gifts", "Personalised Gifts"],
  Parents: ["Gold Coins", "Religious Pendants", "Chains", "Bracelets", "Rings", "Pooja Articles", "Silver Articles", "Health Pendants"],
  Occasion: ["Birthday Gifts", "Anniversary Gifts", "Wedding Gifts", "Housewarming Gifts", "Festive Gifts", "Graduation Gifts", "Promotion Gifts", "Baby Shower Gifts"],
  Corporate: ["Gold Coins", "Silver Coins", "Desk Accessories", "Pen Sets", "Customized Coins", "Mementos", "Trophies", "Premium Sets"],
  Religious: ["Gold Idols", "Silver Idols", "Pooja Items", "Religious Pendants", "Yantra Pendants", "Mala & Chains", "Temple Jewellery", "Spiritual Coins"],
};

export function getGiftingSubcategories(tag) {
  return GIFTING_SUBCATEGORIES[tag] || [];
}

// Wedding/bridal type list — navbar's Wedding mega-menu ku matching data.
// Category select pannina, andha category ku matching bridal types mattum kaatum.
export const WEDDING_SUBCATEGORIES = {
  rings: ["Engagement Rings", "Wedding Rings", "Kundan Rings", "Temple Rings", "Couple Rings", "Antique Rings", "Polki Rings"],
  necklaces: ["Temple Necklaces", "Kundan Necklaces", "Antique Necklaces", "Polki Necklaces", "Traditional Necklaces", "Long Haaram", "Choker Necklaces", "Rani Haar"],
  bangles: ["Gold Bangles", "Kundan Bangles", "Antique Bangles", "Polki Bangles", "Kada Bangles", "Temple Bangles", "Designer Bangles"],
  earrings: ["Jhumka Earrings", "Kundan Earrings", "Temple Earrings", "Chandbali Earrings", "Polki Earrings", "Long Earrings", "Stud Earrings", "Drop Earrings"],
  mangalsutra: ["Traditional Mangalsutra", "Beaded Mangalsutra", "Pendant Mangalsutra", "Short Mangalsutra", "Gold Mangalsutra", "Black Bead Mangalsutra", "Mangalsutra Sets"],
};

export function getWeddingSubcategories(category) {
  return WEDDING_SUBCATEGORIES[category] || [];
}

// Gift Tags sub-list — navbar's Gifting mega-menu ku matching data.
// Admin oru gift tag (Her/Him/Kids...) select pannina, andha tag-oda specific items mattum dropdown la varum.
export const GIFT_TAG_SUBCATEGORIES = {
  her: ["Necklaces", "Earrings", "Rings", "Bracelets", "Pendants", "Bangles", "Mangalsutra", "Nose Pins"],
  him: ["Chains", "Bracelets", "Rings", "Pendants", "Cufflinks", "Tie Pins", "Men's Kada", "Coins & Bars"],
  kids: ["Baby Jewellery", "Chains", "Earrings", "Bracelets", "Nazariya", "Anklets", "Pendants", "ID Bracelets"],
  couple: ["Couple Rings", "Couple Pendants", "Matching Bracelets", "His & Her Sets", "Engagement Gifts", "Anniversary Gifts", "Personalised Gifts"],
  parents: ["Gold Coins", "Religious Pendants", "Chains", "Bracelets", "Rings", "Pooja Articles", "Silver Articles", "Health Pendants"],
  occasion: ["Birthday Gifts", "Anniversary Gifts", "Wedding Gifts", "Housewarming Gifts", "Festive Gifts", "Graduation Gifts", "Promotion Gifts", "Baby Shower Gifts"],
  corporate: ["Gold Coins", "Silver Coins", "Desk Accessories", "Pen Sets", "Customized Coins", "Mementos", "Trophies", "Premium Sets"],
  religious: ["Gold Idols", "Silver Idols", "Pooja Items", "Religious Pendants", "Yantra Pendants", "Mala & Chains", "Temple Jewellery", "Spiritual Coins"],
};

export function getGiftSubcategories(tag) {
  return GIFT_TAG_SUBCATEGORIES[tag?.toLowerCase()] || [];
}